backend:
  name: github
  repo: iRON5/nextjs-netlify
  branch: master
  base_url: https://romco.site
  auth_endpoint: api/auth
  open_authoring: true
  preview_context: Vercel/deployment

media_folder: /public/img
public_folder: img

publish_mode: editorial_workflow

i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - label: Home
    name: home
    i18n: true
    folder: content/home
    preview_path: /{{fields.language}}/home
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - {
          label: 'Publish Date',
          i18n: duplicate,
          name: 'date',
          widget: 'datetime',
        }
      - { label: 'Body', name: 'body', widget: 'markdown', i18n: true }
  - label: About
    name: about
    i18n: true
    folder: content/about
    preview_path: /{{fields.language}}/about
    fields:
      - { label: Title, name: title, i18n: true }
      - {
          label: Publication Date,
          i18n: duplicate,
          name: date,
          widget: datetime,
        }
      - { label: Body, name: body, widget: markdown, i18n: true }
  - label: Blog posts
    name: blog
    i18n: true
    folder: content/posts
    slug: '{{year}}-{{month}}-{{day}}__{{fields.slug}}'
    preview_path: /{{fields.language}}/blog/{{fields.slug}}
    create: true
    fields:
      - {
          label: Title,
          name: title,
          required: true,
          i18n: true,
          pattern: ['.{10,70}', 'Should have 10-70 characters'],
        }
      - { label: URL Slug, i18n: duplicate, name: slug, required: true }
      - {
          label: Publish Date,
          i18n: duplicate,
          name: date,
          widget: datetime,
          required: true,
        }
      - {
          label: Featured Image,
          name: thumbnail,
          widget: image,
          required: true,
          i18n: true,
        }
      - {
          label: Body,
          name: body,
          widget: markdown,
          required: true,
          i18n: true,
        }
